language: go
os: linux
go:
  - 1.x
branches:
  only:
    - main
install:
  - curl -fsSL https://get.pulumi.com/ | bash
  - export PATH="$HOME/.pulumi/bin:$PATH"
before_script:
  - chmod +x ./scripts/*.sh
services:
  - docker
env:
  - PULUMI_ACCESS_TOKEN: $PULUMI_ACCESS_TOKEN
  - ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  - SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

jobs:
  include:
    - stage: pulumi-preview
      script: ./scripts/pulumi-preview.sh
      if: type = pull_request
    - stage: pulumi-up
      script: ./scripts/run-pulumi.sh
      if: type = push
